### ISSUE TITLE
memory not mapped

### ISSUE THREAD

**Issue by CaoQi92** [s-mishra/featuredriven-hawkes#2]
I run this project as the provided tutorial, but found that there are errors like following:
 *** caught segfault ***
address (nil), cause 'memory not mapped'

the detailed process as follows:

> source('rscripts/marked_hawkes.R')
Loading required package: ipoptr
> real_cascade <- read.csv(file = 'example_book.csv', header = T)
> real_cascade[1:10, ]
    X magnitude time
1   1     40989    0
2   2      1445   21
3   3       563   31
4   4       329   33
5   5       555   49
6   6       513   54
7   7     28145   58
8   8       100   62
9   9       164   82
10 10       491   87
> predTime <- 600
> 
> history <- real_cascade[real_cascade$time <= predTime, ]
> history <- history[ , 2:3]
> oldw <- getOption("warn")
> options(warn = -1)
> startParams <- c(K= 1,beta=1, c=250, theta= 1)
> result <- fitParameters(startParams, history)

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call(IpoptRSolve, ret)
 2: ipoptr(x0 = c(K = start$K, beta = start$beta, c = start$c, theta = start$theta),     eval_f = neg.log.likelihood, eval_grad_f = closedGradient,     eval_g = constraint, eval_jac_g = jacobian, eval_jac_g_structure = list(c(1,         2, 3, 4)), lb = lb, ub = ub, constraint_lb = constraint_lb,     constraint_ub = constraint_ub, opts = opts, history = history,     kernel.type = kernel.type)
 3: fitParameters(startParams, history)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 

Note that I have installed the ipopt, including BLAS, LAPACK, ASL, HSL and MUMPS Linear Solver. Is there anything I missed? 
Why this error occurred?

Thank you for your help!

**Comment by s-mishra** [comment]
Issue might be because of using ma27 a linear solver, rather than ma57. We chatted on email too and I believe this was resolved
