### ISSUE TITLE
Ipoptr use in R with R session aborted

### ISSUE THREAD

**Issue by fuentesjtu** [s-mishra/featuredriven-hawkes#4]
I success to install ipoptr in Rstudio with Ubuntu14.04. But when I use the function ipoptr to achieve my program, I meet a bug with RstudioR Session Aborted. Then I try to use the r-base to run the program, and get the result as:

result <- fitParameters(startParams, history)
* caught segfault *

address (nil), cause 'memory not mapped'

Traceback:
 1: .Call(IpoptRSolve, ret)
 2: ipoptr(x0 = c(K = start$K, beta = start$beta, c = start$c, theta = start$theta), eval_f = neg.log.likelihood, eval_grad_f = closedGradient, eval_g = constraint, eval_jac_g = jacobian, eval_jac_g_structure = list(c(1, 2, 3, 4)), lb = lb, ub = ub, constraint_lb = constraint_lb, constraint_ub = constraint_ub, opts = opts, history = history, kernel.type = kernel.type)
 3: fitParameters(startParams, history)
Would you know what is the problem?

**Comment by s-mishra** [comment]
it's the issue of linear solver being used with ipopt
