### ISSUE TITLE
The issue of linear solver being used with ipopt

### ISSUE THREAD

**Issue by fuentesjtu** [s-mishra/featuredriven-hawkes#5]
I just install as ./get ASL, ./getBlas, ./get.Lapack, ./get Metis, ./get Mumps and then

./configure -enable-debug -disable-shared -with-pic

then

make and make install

to success install the package ipoptr.

I really don't know what is the problem of it.

**Comment by s-mishra** [comment]
Try to use solvers provided by hsl, ma57 I believe
