### ISSUE TITLE
Feature data format

### ISSUE THREAD

**Issue by n-gunji** [s-mishra/featuredriven-hawkes#7]
@s-mishra I can not understand the data format. It would be greatly appreciated if you could explain the details.

**Comment by s-mishra** [comment]
There are two files index and data. The index file has the starting and the end index for each cascade. In the data file, each line has the time in seconds from the first tweet in the cascade and the number of followers of the user for that particular tweet.

For example, say you have two retweet cascades of length 55 and 80 then index file should read something like:- 
``` 
start index, end index
1, 55
56,135
```
data file should read like:-
```
time, magnitude
0, 100
2, 56
.
.
.
.
. (line number 55)
0, 47
.
.
.
.(line number 135)
```

**Comment by n-gunji** [comment]
@s-mishra Thank you very much for your quick and detailed reply! I understand how to use them well. 
I'm sorry to bother you again, but could you show me how to use files named `features_*.csv` ?
